version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@ideal-postcodes/api-fixtures"
    versions:
    - 1.3.0
  - dependency-name: "@ideal-postcodes/address-finder"
    versions:
    - 1.8.1
    - 1.8.3
  - dependency-name: core-js-pure
    versions:
    - 3.10.1
    - 3.11.0
  - dependency-name: "@ideal-postcodes/api-typings"
    versions:
    - 2.1.0
  - dependency-name: "@wessberg/rollup-plugin-ts"
    versions:
    - 1.3.10
    - 1.3.14
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.15
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.20.0
    - 4.21.0
  - dependency-name: cypress
    versions:
    - 6.5.0
    - 7.0.1
  - dependency-name: rollup
    versions:
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.42.4
    - 2.45.1
  - dependency-name: core-js
    versions:
    - 3.10.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.17.0
    - 4.19.0
    - 4.20.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.0
    - 11.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
    - 7.13.8
  - dependency-name: "@ideal-postcodes/jsutil"
    versions:
    - 4.0.1
    - 4.2.0
    - 4.3.1
    - 4.3.2
    - 4.3.4
    - 4.3.5
    - 4.3.6
  - dependency-name: typescript
    versions:
    - 4.1.5
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
  registries:
  - npm-registry-registry-npmjs-org
